  spring:
    datasource:
      driverClassName: "org.postgresql.Driver"
      url: "jdbc:postgresql://localhost:5432/sherit"
      username: "as"
      password: "1234"

  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc.time_zone: UTC
        format_sql: true

  sql.init.mode: always
  application.name: shareit
  main.banner-mode: OFF

  logging:
    level:
      org:
        springframework:
          orm.jpa: INFO
          transaction: INFO
          transaction.interceptor: TRACE
          orm.jpa.JpaTransactionManager: DEBUG
        zalando.logbook: TRACE