  spring:
    datasource:
      url: "jdbc:h2:mem:testdb"
      driverClassName: "org.h2.Driver"
      username: "sa"
      password: "password"

  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc.time_zone: UTC
        format_sql: true

  sql.init.mode: always
  application.name: shareit
  main.banner-mode: OFF

  logging.level:
    ru.practicum.shareit: INFO
    org:
      zalando.logbook: TRACE
      springframework:
        orm.jpa: INFO
        transaction: INFO
        transaction.interceptor: TRACE
        orm.jpa.JpaTransactionManager: DEBUG